# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'dariusSonarCloud'
    organization: 'team-2'
    scannerMode: 'MSBuild'
    projectKey: 'project-2-client'
    projectName: 'project-2-client'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: CmdLine@2
  inputs:
    script: |
      npm install -g @angular/cli
      npm install
      ng build --prod
    workingDirectory: '$(System.DefaultWorkingDirectory)/Projects/DeliveryApp/ClientApp'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(acbdb889-c08c-4425-a91a-f10d904bc1ea)'
    appType: 'webAppLinux'
    WebAppName: 'deliveryclient'
    packageForLinux: '$(System.DefaultWorkingDirectory)/Projects/DeliveryApp/ClientApp/dist/ClientApp'

# - task: SonarCloudAnalyze@1

# - task: SonarCloudPublish@1
#   inputs:
#     pollingTimeoutSec: '300'

# - script: |
#     npm install -g @angular/cli
#     npm install
#     ng build --prod
#   displayName: 'npm install and build'

