# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:


- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: CmdLine@2
  inputs:
    script: |
      npm install -g @angular/cli
      npm install
      npm install @auth0/auth0-spa-js
      ng build --prod
    workingDirectory: 'Projects/DeliveryApp/ClientApp'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'dariusSonarCloud'
    organization: 'team-2'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'project-2-client'
    cliSources: 'Projects/DeliveryApp/ClientApp'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.sources=Projects/DeliveryApp/ClientApp
      sonar.tests=Projects/DeliveryApp/ClientApp
      sonar.test.inclusions=**/*.spec.ts
      sonar.typescript.lcov.reportPaths=Projects/DeliveryApp/ClientApp/coverage/lcov.info
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(acbdb889-c08c-4425-a91a-f10d904bc1ea)'
    appType: 'webApp'
    WebAppName: 'deliveryclient'
    packageForLinux: 'Projects/DeliveryApp/ClientApp/dist/ClientApp'

# perform unit-tets and publish test and code coverage results
- script: |
    npx ng test --watch=false --code-coverage
  workingDirectory: 'Projects/DeliveryApp/ClientApp' 

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TESTS-*.xml'

- task: PublishCodeCoverageResults@1
  displayName: 'publish code coverage report'
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: 'Projects/DeliveryApp/ClientApp/coverage/cobertura-coverage.xml'
    failIfCoverageEmpty: true  

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'