# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'dariusSonarCloud'
    organization: 'team-2'
    scannerMode: 'MSBuild'
    projectKey: 'project-2'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Projects/DeliveryApp/DeliveryApp.Web/DeliveryApp.Web.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'Projects/DeliveryApp/DeliveryApp.Test/DeliveryApp.Test.csproj'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'Projects/DeliveryApp/DeliveryApp.Web/DeliveryApp.Web.csproj'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(acbdb889-c08c-4425-a91a-f10d904bc1ea)'
    appType: 'webApp'
    WebAppName: 'DariusVallejoPipelineDemo'
    packageForLinux: '$(System.DefaultWorkingDirectory)/Projects/DeliveryApp/DeliveryApp.Web/bin/Debug/netcoreapp3.1/publish.zip'